spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
jwt:
  secretKey: "This Data Must Be Managed By Secret NOT HERE THIS IS JUST EXAMPLE"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE